### PR TITLE
Allow new configuration for F Prime

### LINKED ISSUE #2659: Cmake: Config directory not living at project include roots fails to build correctly
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

A description of the problem with sufficient detail to understand the issue.

## Context / Environment

Execute `fprime-util version-check` and share the output.

```
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python version: 3.10.12
CMake version: 3.22.1
Pip version: 22.0.2
Pip packages:
    fprime-tools==3.4.4
    fprime-gds==3.4.3
    fprime-fpp-*==2.1.0a5
```

## How to Reproduce

1. 
2.
3.

## Expected Behavior

A description of the expected behavior.

### LINKED ISSUE #2914: Have fprime-util new deployment copy `./config` directory.
| | |
|:---|:---|
|**_F´ Version_**| [v3.4.3](https://github.com/nasa/fprime/releases/tag/v3.4.3) |
|**_Affected Component_**| n/a  |
---
## Feature Description

`fprime-util new deployment` should copy the config directory from the F Prime sub-repo and create a `settings.ini` file to point to it.

## Rationale

Most projects will end up copying these anyway, so make copies and place them in the deployment directory.

### LINKED ISSUE #3209: Cleaner Configuration Handling
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Clean up how the `config` directory maps to F Prime.

### LINKED ISSUE #3210: Place F Prime Config Under `fprime/default/config`
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Currently the following include structures are valid:

`#include <config/file.hpp>` and `#include <file.hpp>` this leaves some ambiguity on how config files are included.

We should:

- [ ] Move config to `default/config`
- [ ] Update all includes to use `config/file.hpp` for clarity
- [ ] Update F Prime to use the configuration directory `default`
- [ ] Update autocoding config to follow this structure

### LINKED ISSUE #3211: Place F Prime Config Under fprime/default/config
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Allow projects to use configuration overlays.

Depends on #3210.  

We can add both `default` and project config to the HPP include path.  That way projects only need maintain configuration for specifically what they are changing

### LINKED ISSUE #3369: Merge Fw/Types, Fw/Cfg, and config
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

Fw Types depends on config, config will soon depend on Fw/Types via autocode.  Merge them into one unit.

### LINKED ISSUE #3439: settings.ini config_directory does not work if value is not config
| | |
|:---|:---|
| 3.6.1 | |
|fprime/cmake|   |
---
## Problem Description

`settings.ini` allows `config_directory` entry to specify directory for config files.  But if the value does not end in `config` build fails.

## Context / Environment

Execute `fprime-util version-check` and share the output.

```
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-5.10.0-28-amd64-x86_64-with-glibc2.36
Python version: 3.11.2
CMake version: 3.25.1
Pip version: 23.0.1
Pip packages:
    fprime-tools==3.6.1
    fprime-gds==3.6.1
    fprime-fpp-*==2.3.0
Project submodules:
    https://github.com/nasa/fprime.git @ v3.6.2
```

## How to Reproduce

1. `mv config config-native`
2. edit `settings.ini` to change location of (local) config directory
3. `fprime-util generate` followed by `fprime-util build`

I get:
```
build-fprime-automatic-native/F-Prime/Svc/PolyIf/PolyPortAc.hpp:22:10: fatal error: config-native/PolyDbEntryEnumAc.hpp: No such file or directory
   22 | #include "config-native/PolyDbEntryEnumAc.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and note that `build-fprime-native-automatic` has a `config` directory but no `config-native` directory.

## Expected Behavior

clean build

### LINKED ISSUE #3454: Build failure after updating to latest fprime devel commit
| | |
|:---|:---|
|**_F´ Version_**| 0659f0940b6a570a116e80cb785e715c1543e8b9 |
|**_Affected Component_**| build system |
---
## Problem Description

When I update my fprime version from dcfc109b5bc917115fead652e9ba68cb15900858 to 0659f0940b6a570a116e80cb785e715c1543e8b9 (the latest commit at this moment), I stop being able to build my project due to a "No build root found" error.

```
# fprime-util generate --ninja
[INFO] Generating build directory at: /workspaces/[...]/build-fprime-automatic-[...]
[INFO] Using toolchain file /workspaces/[...]/cmake/toolchain/[...].cmake for platform default
-- The C compiler identification is Clang 19.1.1
-- The CXX compiler identification is Clang 19.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [python3] python3 found at: /usr/bin/python3
-- [fpp-tools] fpp-depend found at: /usr/local/bin/fpp-depend
-- [fpp-tools] fpp-to-xml found at: /usr/local/bin/fpp-to-xml
-- [fpp-tools] fpp-to-cpp found at: /usr/local/bin/fpp-to-cpp
-- [fpp-tools] fpp-to-dict found at: /usr/local/bin/fpp-to-dict
-- [fpp-tools] fpp-locate-defs found at: /usr/local/bin/fpp-locate-defs
-- [FPRIME] Module locations: /workspaces/[...]/lib/fprime;/workspaces/[...];/workspaces/[...]
-- [FPRIME] Configuration module: /workspaces/[...]/config
-- [FPRIME] Installation directory: /workspaces/[...]/build-artifacts
-- Target build toolchain/platform: [...]/[...]
-- Including /workspaces/[...]/cmake/platform/[...].cmake
-- [LIBRARY] Including library [...] at /workspaces/[...]
-- [sub-build] Performing sub-build: info-cache
-- [sub-build] Generating: info-cache with target/fpp_locs;target/fpp_depend
CMake Error at lib/fprime/cmake/utilities.cmake:595 (message):
  [sub-build] Failed to generate: info-cache:

  CMake Error at lib/fprime/cmake/utilities.cmake:426 (message):

    No build root found for: /workspaces/[...]

  Call Stack (most recent call first):

    lib/fprime/cmake/utilities.cmake:461 (get_nearest_build_root)
    lib/fprime/cmake/FPrime.cmake:212 (get_module_name)
    CMakeLists.txt:29 (fprime_setup_included_code)

  -- The C compiler identification is Clang 19.1.1

  -- The CXX compiler identification is Clang 19.1.1

  -- Detecting C compiler ABI info

  -- Detecting C compiler ABI info - failed

  -- Detecting C compile features

  -- Detecting C compile features - done

  -- Detecting CXX compiler ABI info

  -- Detecting CXX compiler ABI info - failed

  -- Detecting CXX compile features

  -- Detecting CXX compile features - done

  -- [python3] python3 found at: /usr/bin/python3

  -- [fpp-tools] fpp-depend found at: /usr/local/bin/fpp-depend

  -- [fpp-tools] fpp-to-xml found at: /usr/local/bin/fpp-to-xml

  -- [fpp-tools] fpp-to-cpp found at: /usr/local/bin/fpp-to-cpp

  -- [fpp-tools] fpp-to-dict found at: /usr/local/bin/fpp-to-dict

  -- [fpp-tools] fpp-locate-defs found at: /usr/local/bin/fpp-locate-defs

  -- [FPRIME] Module locations:
  /workspaces/[...]/lib/fprime;/workspaces/[...];/workspaces/[...]


  -- [FPRIME] Configuration module: /workspaces/[...]/config

  -- [FPRIME] Installation directory: /workspaces/[...]/build-artifacts

  -- Target build toolchain/platform: [...]/[...]

  -- Including
  /workspaces/[...]/cmake/platform/[...].cmake


  -- [LIBRARY] Including library [...] at
  /workspaces/[...]

  -- [LIBRARY] Adding modules from F´ framework

  -- Configuring incomplete, errors occurred!
Call Stack (most recent call first):
  lib/fprime/cmake/sub-build/sub-build.cmake:40 (execute_process_or_fail)
-- Configuring incomplete, errors occurred!
  lib/fprime/cmake/FPrime.cmake:163 (run_sub_build)
  lib/fprime/cmake/FPrime.cmake:247 (fprime_initialize_build_system)
  CMakeLists.txt:13 (include)


[ERROR] CMake erred with return code 1. Partial build cache remains. Run purge to clean-up.
```

## Context / Environment

Execute `fprime-util version-check` and share the output.

```
[root@c473577b197b lib]# fprime-util version-check
Operating System: Linux
CPU Architecture: x86_64
Platform: Linux-4.18.0-553.34.1.el8_10.x86_64-x86_64-with-glibc2.34
Python version: 3.9.21
CMake version: 3.26.5
Pip version: 21.3.1
Pip packages:
    fprime-tools==3.6.1
    fprime-gds==3.6.1
    fprime-fpp-*==3.0.0a7
Project submodules:
    https://github.com/nasa/fprime.git @ v3.6.0-53-g0659f0940
```

## How to Reproduce

See above.

## Expected Behavior

Updating to the latest version of F Prime should not fail my build. If something significant changed that I now need to accommodate in my project, I expect to find something in the pull request that introduced the problem (#3422) that explains what I need to change.

### LINKED ISSUE #3500: Build a `config` Module Within Build Cache
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|  |
---
## Feature Description

Build a `config` module that includes current `config`, `Fw_Types`, `Fw_Cfg`, and the platform modules.  This is because all three modules are interdependent.

### LINKED ISSUE #3564: Remove FW_BAREMETAL_SCHEDULER from FpConfig.h
These lines are still present in FpConfig.h:

```
#ifndef FW_BAREMETAL_SCHEDULER
#define FW_BAREMETAL_SCHEDULER \
    0  //!< Indicates whether or not a baremetal scheduler should be used. Alternatively the Os scheduler is used.
#endif
```

However, it appears that FW_BAREMETAL_SCHEDULER is no longer used anywhere, and that other mechanisms are now in place for the behavior that it previously offered.

Let's remove this unused setting so that it doesn't result in any confusion.

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |

---

### CODE REVIEW

**Comment by LeStarch** [comment]
# Breaking Change Summary

- `config` dependencies should be be switched to `Fw_Types`
- Config includes should be switched to use `config/*`
- Configuration is now a proper F Prime module.  Use `register_fprime_configuration(....)` to add a config module or override.

File: Fw/Types/CMakeLists.txt [hunk 1]
```diff
@@ -18,9 +18,10 @@ set(SOURCE_FILES
   "${CMAKE_CURRENT_LIST_DIR}/StringUtils.cpp"
   "${CMAKE_CURRENT_LIST_DIR}/StringToNumber.cpp"
   "${CMAKE_CURRENT_LIST_DIR}/Types.fpp"
+  "${CMAKE_CURRENT_LIST_DIR}/snprintf_format.cpp"
```
Comment (LeStarch) [inline Fw/Types/CMakeLists.txt]: What's this?

File: Fw/Types/CMakeLists.txt [hunk 2]
```diff
@@ -18,9 +18,10 @@ set(SOURCE_FILES
...
 )
 set(MOD_DEPS
-  Fw/Cfg
+  __fprime_config
```
Comment (LeStarch) [inline Fw/Types/CMakeLists.txt:23]: Since I cannot do a generator on a global property, I have to use a hidden target name

File: cmake/FPrime.cmake [hunk 3]
```diff
@@ -6,11 +6,14 @@
 # support. This file includes the cmake build system setup for building like fprime.
 ####
 include_guard()
+cmake_policy(SET CMP0118 NEW)
```
Comment (LeStarch) [inline cmake/FPrime.cmake]: Needed ?

File: cmake/target/build.cmake [hunk 4]
```diff
@@ -69,7 +69,7 @@ function(fprime__internal_TECH_DEBT_module_setup BUILD_MODULE_NAME MODULE_NAME_H
     #
     # This should be done per-target using IMPLEMENTATION_OVERRIDES supplied to API registration call and should not
     # be set to the current module.
-    if (NOT ${MODULE_TYPE} STREQUAL "Library")
+    if (NOT ${MODULE_TYPE} STREQUAL "Library" AND NOT ${MODULE_TYPE} STREQUAL "Interface")
```
Comment (LeStarch) [inline cmake/target/build.cmake]: Delete

File: cmake/utilities.cmake [hunk 5]
```diff
@@ -860,19 +861,20 @@ function(recurse_target_properties CMAKE_BUILD_TARGET_NAME PROPERTY_NAMES TRANSI
             fprime_cmake_ASSERT("'${LINK}' is a null dependency of '${CMAKE_BUILD_TARGET_NAME}'" LINK)
             # Recurse through each link and append the recursively determined additions to the list
             # while ensuring there are no duplicates
+            set(__PARENT_RECURSED "${CMAKE_BUILD_TARGET_NAME}")
```
Comment (LeStarch) [inline cmake/utilities.cmake]: Remove

**Review by LeStarch — COMMENTED** [review]
Add to break notes about new config reg

File: cmake/settings/ini.cmake [hunk 6]
```diff
@@ -22,7 +22,6 @@ set(FPRIME_UTIL_CRITICAL_LIST
     "FPRIME_LIBRARY_LOCATIONS"
     "FPRIME_PROJECT_ROOT"
     "FPRIME_ENVIRONMENT_FILE"
-    "FPRIME_CONFIG_DIR"
```
Comment (thomas-bc) [inline cmake/settings/ini.cmake:25]: Are you tracking changes that the ongoing refactor might induce on fprime-tools (and less likely GDS/FPP ?). Since this item is expected by fprime-tools, we probably should clean that up on tools

File: docs/user-manual/framework/configuring-fprime.md [hunk 7]
```diff
@@ -380,15 +380,6 @@ Table 47 describes other user settings.
 > [!NOTE]
 > The following settings are defined by the build system and are in `FpConfig.hpp` to provide a default off value. These must be set by the build system as the setting works in unison with other modules that the build system includes when enabling these settings.
 
-Table 48 describes settings defined by the build system that should never be hand-set.
```
Comment (thomas-bc) [inline docs/user-manual/framework/configuring-fprime.md:383]: Not necessarily needed right now but it could be good to walk through this and make sure it's up to date, + add a section referencing the new `reigster_fprime_config()` API and all. Maybe for a ROSES ticket?

**Review by thomas-bc — APPROVED** [review]
