### ISSUE TITLE
Website build broke following pygments upgrade

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime#4918]
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

In our website CI:

```
  File "/path/to/python3.11/site-packages/pygments/formatters/html.py", line 434, in __init__
    self.filename = html.escape(self._decodeifneeded(options.get('filename', '')))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/html/__init__.py", line 19, in escape
    s = s.replace("&", "&amp;") # Must be done first!
        ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
error: Command '['mkdocs', 'build', '--clean', '--config-file', './fprime/docs/mkdocs.yml']' returned non-zero exit status 1.
```

Introduced by https://github.com/nasa/fprime/pull/4916

See https://github.com/pygments/pygments/issues/3076 for more details.

**Comment by thomas-bc** [comment]
Fixed internally - added byproducts in https://github.com/nasa/fprime/pull/4943
